services:
  postgres:
    image: 'postgres:latest'
    container_name: '{ YOUR_POSTGRES_CONTAINER_NAME }'  # <-- FILL THIS LINE
    environment:
      - 'POSTGRES_DB={ YOUR_DATABASE }'                 # <-- FILL THIS LINE
      - 'POSTGRES_PASSWORD={ YOUR_PASSWORD }'           # <-- FILL THIS LINE
      - 'POSTGRES_USER={ YOUR_USERNAME }'               # <-- FILL THIS LINE
      - 'TZ=Asia/Ho_Chi_Minh'
    ports:
      - '9876:5432'
    volumes:
      - { YOUR_POSTGRES_VOLUME_NAME }:/var/lib/postgresql
  redis:
    image: 'redis:latest'
    container_name: '{ YOUR_REDIS_CONTAINER_NAME }'     # <-- FILL THIS LINE
    environment:
      - 'TZ=Asia/Ho_Chi_Minh'
    ports:
      - '6379:6379'
    volumes:
      - { YOUR_REDIS_VOLUME_NAME }:/data                # <-- FILL THIS LINE
volumes:
  { YOUR_POSTGRES_VOLUME_NAME }:                        # <-- FILL THIS LINE
  { YOUR_REDIS_VOLUME_NAME }:                           # <-- FILL THIS LINE