spring:
  application:
    name: j3be
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: j3pg
#    password: password4j3pg
#    url: jdbc:postgresql://localhost:5432/j3pg
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true