spring:
  application:
    name: j3be
  datasource:
    driver-class-name: org.postgresql.Driver
    username: { YOUR_USERNAME }                             # <-- FILL THIS LINE
    password: { YOUR_PASSWORD }                             # <-- FILL THIS LINE
    url: jdbc:postgresql://localhost:9876/{ YOUR_DATABASE } # <-- FILL THIS LINE
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
joho3:
  persistence:
    system-id: { YOUR SYSTEM USER ID }                      # <-- FILL THIS LINE