spring:
  application:
    name: j3be
  datasource:
    driver-class-name: org.postgresql.Driver
    username: { YOUR_USERNAME }                             # <-- FILL THIS LINE
    password: { YOUR_PASSWORD }                             # <-- FILL THIS LINE
    url: jdbc:postgresql://localhost:9876/{ YOUR_DATABASE } # <-- FILL THIS LINE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
